# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=24)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('dtinicio', models.DateField()),
                ('dtfim', models.DateField()),
            ],
        ),
    ]
