# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161126_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balcao',
            name='itens',
        ),
        migrations.AddField(
            model_name='item',
            name='balcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Balcao'),
        ),
    ]
