# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161126_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.CharField(max_length=3),
        ),
    ]
